### PR TITLE
Consolidate CI and add Bors config

### PR DESCRIPTION
**Pull request by nicholastmosher**
- Consolidate some jobs in CI to make it simpler
- Add Bors config for merging

### CODE REVIEW

**Comment by nicholastmosher** [comment]
bors ping

**Comment by nicholastmosher** [comment]
@sehz once this CI passes you can `bors r+`

**Review by sehz — APPROVED** [review]
nice job!

**Comment by sehz** [comment]
certs have expired.  you can re-generate certs or I can do it

**Comment by sehz** [comment]
rebase and CI failure will go away

**Comment by nicholastmosher** [comment]
Hmm, for some reason one of the jobs just didn't even start for like 20 mins. But none of the jobs take more than like 5 mins, let's just try again.

bors r+

**Review by sehz — APPROVED** [review]

**Pull request merged**
